import { Cart, CartEventName } from "../../lib/gen/cart.ts";
import { convertFilenameToTargetFilename } from "../common.ts";

const deno = new Cart();

const makeComment = () => {
  const year = new Date().getFullYear();
  const comment = `// Generated by Fart © ${year}`;
  return comment;
};

deno.on(
  CartEventName.FileStart,
  (event) => {
    event.code.append(makeComment());
  },
);

deno.on(
  CartEventName.Import,
  (event) => {
    if (event.dependencies.length === 0) return event.code.skip();
    const targetFilename = convertFilenameToTargetFilename(event.source);
    const serializedDeps = event.dependencies.join(", ");
    const importation =
      `import type { ${serializedDeps} } from "${targetFilename}";`;
    event.code.append(importation);
  },
);

deno.on(
  CartEventName.StructOpen,
  (event) => {
    event.code.append(`export interface ${event.identifier} {`);
  },
);

deno.on(
  CartEventName.SetProperty,
  (event) => {
    const assignment = event.required ? ":" : "?:";
    const property = event.value === undefined
      ? event.identifier + assignment + " {"
      : event.identifier + assignment + " " + event.value + ";";
    event.code.append(property);
  },
);

deno.on(CartEventName.StructClose, (event) => {
  event.code.append("}");
});

deno.on(
  CartEventName.FileEnd,
  (event) => {
    event.code.append(makeComment());
  },
);

deno.on(
  CartEventName.Comment,
  (event) => {
    event.code.append(`// ${event.comment}`);
  },
);

export default deno;
