export enum Lexicon {
  Identifier,
  Nester,
  Denester,
  OpeningAngle,
  ClosingAngle,
  Setter,
  RequiredMarker,
  RequiredSetter,
  TypeDefiner,
  DepoDefiner,
  LoadDefiner,
  Commenter,
  Separator,
  Spacer,
  LineBreaker,
  LineBreaker2,
  StringMarker,
  StringMarker2,
  StringMarker3,
  StringLiteral,
  Modifier,
  Comment,
  EOF,
}

export const LEXICON = {
  [Lexicon.Nester]: "{",
  [Lexicon.Denester]: "}",
  [Lexicon.OpeningAngle]: "<",
  [Lexicon.ClosingAngle]: ">",
  [Lexicon.Setter]: ":",
  [Lexicon.RequiredMarker]: "*",
  [Lexicon.RequiredSetter]: "*:",
  [Lexicon.TypeDefiner]: "type",
  [Lexicon.DepoDefiner]: "depo",
  [Lexicon.LoadDefiner]: "load",
  [Lexicon.Commenter]: ";",
  [Lexicon.Separator]: ",",
  [Lexicon.Spacer]: " ",
  [Lexicon.LineBreaker]: "\n",
  [Lexicon.LineBreaker2]: "\r",
  [Lexicon.StringMarker]: "\`",
  [Lexicon.StringMarker2]: "'",
  [Lexicon.StringMarker3]: '"',
  [Lexicon.Modifier]: "%",
  [Lexicon.Comment]: "COMMENT",
  [Lexicon.EOF]: "",
} as const;
