// Generated by Fart © 2021
export interface Pokeball {
  id: string;
  odds: number;
  used: boolean;
  throw: (a: string) => Promise<boolean>;
}
export interface Pokemon {
  name: string;
  num: number;
  ball?: Pokeball;
  catch: (a: Pokeball) => Promise<boolean>;
}
export interface PC {
  mons: Array<Pokemon>;
}
export interface DexEntry {
  name: string;
  num: number;
  summary: string;
  caught: boolean;
  types: {
    type1: string;
    type2?: string;
  }
}
export interface Dex {
  national: Record<number, DexEntry>;
  register: (a: number) => void;
}
export interface Bag {
  dex: Dex;
  balls: Array<Pokeball>;
}
// Generated by Fart © 2021
