// Generated by Fart © 2021
export interface Pokeball {
  id: string;
  odds: number;
  hello1?: used;
  *:?: throw;
  *:?: %;
  <?: ,;
  async?: boolean;
  >?: type;
  Pokemon?: name;
  *:?: num;
  *:?: ball;
  :?: catch;
  *:?: %;
  <?: ,;
  async?: boolean;
  >?: type;
  PC?: mons;
  *:?: %;
  Pokemon?: type;
  DexEntry?: name;
  *:?: num;
  *:?: summary;
  *:?: caught;
  *:?: types;
  *:?: type1;
  *:?: type2;
  :?: };
}
export interface Dex {
  national: Record<number, DexEntry>;
  register: (a: number) => void;
}
export interface Bag {
  dex: Dex;
  balls: Array<Pokeball>;
}
// Generated by Fart © 2021
