export enum Lexicon {
  Identifier,
  Nester,
  Denester,
  OpeningAngle,
  ClosingAngle,
  Setter,
  RequiredMarker,
  TypeDefiner,
  DepoDefiner,
  ImpoDefiner,
  Commenter,
  Separator,
  Spacer,
  LineBreaker,
  LineBreaker2,
  StringMarker,
  StringLiteral,
  EOF,
}

export const LEXICON = {
  [Lexicon.Nester]: "{",
  [Lexicon.Denester]: "}",
  [Lexicon.OpeningAngle]: "<",
  [Lexicon.ClosingAngle]: ">",
  [Lexicon.Setter]: ":",
  [Lexicon.RequiredMarker]: "*",
  [Lexicon.TypeDefiner]: "type",
  [Lexicon.DepoDefiner]: "depo",
  [Lexicon.ImpoDefiner]: "impo",
  [Lexicon.Commenter]: ";",
  [Lexicon.Separator]: ",",
  [Lexicon.Spacer]: " ",
  [Lexicon.LineBreaker]: "\n",
  [Lexicon.LineBreaker2]: "\r",
  [Lexicon.StringLiteral]: "\`",
  [Lexicon.EOF]: "",
}