import {
  Cartridge,
  CartridgeEvent,
  CartridgeEventContext,
  Modifier,
  PropertyDefinition,
  ReservedType,
} from "./cartridge.ts";

export const generateTypeScriptCartridge = (
  options?: { implFile?: string },
) => {
  const typemap = {
    [ReservedType.Omit]: "any",
    [ReservedType.Number]: "number",
    [ReservedType.String]: "string",
    [ReservedType.Boolean]: "boolean",
    [ReservedType.Default]: "any",
    [Modifier.Array]: (inner: string) => `Array<${inner}>`,
    [Modifier.Async]: (inner: string) => `Promise<${inner}>`,
    [Modifier.Dictionary]: (key: string, val: string) =>
      `Record<${key}, ${val}>`,
    [Modifier.Function]: (input: string, output: string) =>
      `(_: ${input}) => ${output}`,
  };

  const getPropTypeString = (def: PropertyDefinition): string => {
    if (def.value) return def.value;
    if (def.struct) return "Record<string, any>"; // For complex inner structs
    if (def.tuple) {
      if (def.tuple.length === 0) return "[]";
      return `[${def.tuple.map((t) => getPropTypeString(t.value)).join(", ")}]`;
    }
    return "any";
  };

  const handlers = {
    [CartridgeEvent.FileStart]: () => `// Auto-generated by Fart Transpiler\n`,
    [CartridgeEvent.Comment]: () => null, // Omit the generic comment hook to let specifically targeting comments run
    [CartridgeEvent.InlineComment]: (
      event: CartridgeEventContext<CartridgeEvent.InlineComment>,
    ) =>
      event.data?.comments.map((comment: string) => `// ${comment}`).join(
        "\n",
      ) ?? null,
    [CartridgeEvent.MultilineComment]: (
      event: CartridgeEventContext<CartridgeEvent.MultilineComment>,
    ) =>
      `/**\n${
        event.data?.comments.map((comment: string) => ` * ${comment}`).join(
          "\n",
        )
      }\n */`,
    [CartridgeEvent.Load]: (
      event: CartridgeEventContext<CartridgeEvent.Load>,
    ) =>
      `import { ${
        event.data?.dependencies.join(", ")
      } } from "${event.data?.source}";`,
    [CartridgeEvent.StructOpen]: (
      event: CartridgeEventContext<CartridgeEvent.StructOpen>,
    ) => {
      if (!event.data) return null;
      const parts = [];
      if (event.data.comments.length > 0) {
        parts.push(
          `/**\n${
            event.data.comments.map((comment: string) => ` * ${comment}`).join(
              "\n",
            )
          }\n */`,
        );
      }
      parts.push(`export interface ${event.data.name} {`);
      return parts.join("\n");
    },
    [CartridgeEvent.SetProperty]: (
      event: CartridgeEventContext<CartridgeEvent.SetProperty>,
    ) => {
      if (!event.data) return null;
      const parts = [];
      if (event.data.comments.length > 0) {
        if (event.data.comments.length === 1) {
          parts.push(`// ${event.data.comments[0]}`);
        } else {
          parts.push(
            `/**\n${
              event.data.comments.map((comment: string) => ` * ${comment}`)
                .join(
                  "\n",
                )
            }\n */`,
          );
        }
      }

      const optionalFlag = event.data.definition.optional ? "?" : "";

      parts.push(
        `${event.data.name}${optionalFlag}: ${
          getPropTypeString(event.data.definition)
        };`,
      );
      return parts.join("\n");
    },
    [CartridgeEvent.StructClose]: () => `}`,
    [CartridgeEvent.FileEnd]: () => {
      if (options?.implFile) {
        return `\nimport Impl from "${options.implFile}";\nexport default Impl;`;
      }
      return "";
    },
  };

  return new Cartridge(typemap, handlers);
};
