import { FartDepartment } from "./fart_department.ts";
import { FakeIODepartment } from "../../io/ts/fake_io_department.ts";
import { assertEquals } from "../../../deps/std/testing.ts";

Deno.test("Initializes successfully", () => {
  const fart = new FartDepartment(new FakeIODepartment());
  assertEquals(fart, fart);
});

Deno.test("Successfully compile Fart file to TypeScript", async () => {
  const fart = new FartDepartment(new FakeIODepartment());
  const result = await fart.compile({
    filepath: "ex/pokemon/mod.fart",
    cartridge_id: "ts",
  });
  assertEquals(
    result,
    "// Generated by Fart © 2021\n// Generated by Fart © 2021\n",
  );
});
